Harshksaw/LMS-App

Backend/controllers/Quiz.js
KrishnaAcademyAPP/app/(routes)/quiz/quiz.details.tsx
KrishnaAcademyAPP/app/_layout.tsx
KrishnaAcademyAPP/screens/search/search.screen.tsx
KrishnaAcademyAPP/utils/uri.tsx

This commit modifies the code in the `getQuizbyId` function of the `Quiz.js` controller file. It adds the `populate` method to the `Quiz.findById` query to populate the "Questions" field of the returned quiz object. This change ensures that the quiz object includes the associated questions, providing more comprehensive data when retrieving a quiz by its ID.

refactor: Populate "Questions" field when fetching quiz by ID

---

Backend/controllers/Quiz.js
Backend/models/Questions.js
Backend/routes/Quiz.js
KrishnaAcademyAPP/app/(routes)/quiz/quiz.details.tsx

This commit updates the `Quiz.js` controller file to restructure the question options. The `updateQuestionOptions` function is added to iterate through all quizzes and their associated questions. Each question's options are transformed from individual fields (optionA, optionB, optionC, optionD) to an options object. The old option fields are removed, and the updated questions are saved individually. This change improves the organization and readability of the code.

refactor: Restructure question options in Quiz.js controller

---

Backend/index.js
Backend/models/Questions.js
KrishnaAcademyAPP/app/(routes)/quiz/quiz.details.tsx

This commit adds the necessary code to enable file upload functionality using AWS S3. It includes the installation of the required dependencies, configuration of the S3 client, and implementation of the file upload route. The uploaded file is stored in an S3 bucket and a presigned URL is generated for the file. This feature enhances the application by allowing users to upload files and securely store them in the cloud.

App-Refactor

---

.vscode/settings.json
Backend/controllers/CourseMaterials.js
Backend/controllers/Payment.js
Backend/controllers/Quiz.js
Backend/controllers/SubSection.js
Backend/models/Questions.js
Backend/models/Quiz.js
Backend/models/User.js
Backend/models/material.js

This commit adds the "isPaid" and "price" fields to the StudyMaterial and Quiz models. In the "material.js" and "Quiz.js" files, the fields are defined as optional Boolean and Number types respectively. This enhancement allows for the differentiation of paid and free study materials and quizzes, and provides a way to set the price for paid materials and quizzes.

refactor: Add isPaid and price fields to StudyMaterial and Quiz models

---

.vscode/settings.json
AdminDashboard/src/pages/AddQuiz.tsx
AdminDashboard/src/pages/Home.jsx
AdminDashboard/src/pages/MyQuiz.tsx
AdminDashboard/src/pages/StudyMaterials.tsx
AdminDashboard/src/services/apis.js
Backend/controllers/Quiz.js
Backend/index.js
Backend/routes/Course.js
Backend/routes/Quiz.js
Backend/routes/studymaterial.js
KrishnaAcademyAPP/app/(routes)/studymaterials/index.tsx
KrishnaAcademyAPP/app/_layout.tsx
KrishnaAcademyAPP/components/Payment/PaymentComponent.tsx
KrishnaAcademyAPP/components/pdfmodal.tsx
KrishnaAcademyAPP/components/studymaterials.tsx
KrishnaAcademyAPP/package-lock.json
KrishnaAcademyAPP/package.json
KrishnaAcademyAPP/screens/home/home.screen.tsx
KrishnaAcademyAPP/utils/uri.tsx
Readme.md
package-lock.json

This commit updates the MyQuiz page in the AdminDashboard application. The modified quiz name is now displayed correctly by replacing spaces with hyphens. This enhancement improves the visual presentation of the quiz name and ensures consistency throughout the application.

Admin-refactor

---

KrishnaAcademyAPP/app/(drawer)/(tabs)/_layout.js
KrishnaAcademyAPP/app/(drawer)/(tabs)/feed/_layout.js
KrishnaAcademyAPP/app/(drawer)/(tabs)/feed/index.js
KrishnaAcademyAPP/app/(drawer)/(tabs)/feed/new.js
KrishnaAcademyAPP/app/(drawer)/(tabs)/profile.js
KrishnaAcademyAPP/app/(drawer)/_layout.js
KrishnaAcademyAPP/app/(drawer)/favourites.js
KrishnaAcademyAPP/app/(drawer)/settings.js
KrishnaAcademyAPP/app/(routes)/enrolled-courses/index.tsx
KrishnaAcademyAPP/app/(tabs)/index.tsx
KrishnaAcademyAPP/app/Drawer.tsx
KrishnaAcademyAPP/app/_layout.tsx
KrishnaAcademyAPP/components/header/header.tsx
KrishnaAcademyAPP/package-lock.json
KrishnaAcademyAPP/package.json

This pull request adds new pages for the feed, settings, favourites, and profile sections of the app. These pages are implemented as functional components and include basic UI elements such as text and buttons. They enhance the navigation and user experience of the app by providing dedicated screens for each section.

Add new pages for feed, settings, favourites, and profile

---

AdminDashboard/src/App.jsx
AdminDashboard/src/components/common/Navbar.jsx

This commit updates the routes in the App component to include a new route for the Login page and separates the existing route for the Home page. The Login page is now set as the default route ("/") and the Home page has its own dedicated route ("/home"). This change improves the navigation flow of the application by providing a separate route for the login functionality.
Changes:
- Updated route to render Login component for "/"
- Added new route to render Home component for "/home"

feat: Update routes to include Login page and separate Home page

---

.vscode/settings.json
AdminDashboard/package-lock.json
AdminDashboard/package.json
AdminDashboard/src/App.jsx
AdminDashboard/src/components/core/Quiz/timer.tsx
AdminDashboard/src/components/tables/quizTable.jsx
AdminDashboard/src/pages/AddQuiz.tsx
AdminDashboard/src/pages/EditQuiz.tsx
AdminDashboard/src/pages/MyQuiz.tsx
AdminDashboard/src/services/apis.js
Backend/controllers/Quiz.js
Backend/controllers/courseBundleController.js
Backend/routes/Quiz.js

This pull request includes updates to the npm dependencies, the addition of the react-time-picker library for the quiz timer feature, and improvements to the UI text. It also adds functionality to edit and view questions, as well as routes and controllers for initializing quizzes, updating quizzes, creating questions, and updating question options. Additionally, it fixes issues with the isQuizId initialization and the handleSaveQuestion logic. The Quiz.js file is updated to sort quizzes by creation date, and EditQuiz.tsx is fixed for formatting and removal of unused code. Finally, commented out code and an unused route in Quiz.js are removed.

Add quiz timer feature and update UI text

---

AdminDashboard/src/components/core/User/User.tsx
AdminDashboard/src/pages/EditQuiz.tsx
AdminDashboard/src/services/apis.js
Backend/controllers/Auth.js
Backend/controllers/Quiz.js
Backend/routes/User.js

This pull request includes several commits that add functionality to the EditQuiz.tsx file, allowing users to add new questions to a quiz. Additionally, it fixes some typos in the EditQuiz.tsx and Quiz.js files. The changes in the code are aimed at improving the user experience and ensuring the accuracy of the quiz data.

Add functionality to add a new question in EditQuiz.tsx and fix typos in EditQuiz.tsx and Quiz.js

---

.vscode/settings.json
AdminDashboard/src/components/core/User/UserCourses.tsx
AdminDashboard/src/services/apis.js
Backend/controllers/Auth.js
Backend/controllers/courseBundleController.js
Backend/models/User.js
Backend/routes/User.js
Backend/routes/courseBundle.js

This commit updates the User model in the Backend to use the correct references for the quizes and studyMaterials fields. The references were previously set to "Course" instead of "Quiz" and "StudyMaterial" respectively. This change ensures that the User model correctly references the Quiz and StudyMaterial models, improving the accuracy and maintainability of the codebase.

Admin_Dash

---

AdminDashboard/src/pages/EditQuiz.tsx

This commit fixes a typo in the EditQuiz component where the question object was missing closing quotes for the "hin" property. The correct code is now added, ensuring that the question object is properly formatted. This change improves the functionality and maintainability of the EditQuiz component.

refactor: Fix typo in EditQuiz component

---

AdminDashboard/src/pages/EditQuiz.tsx

This commit updates the Quiz model to use the latest version (v2) of the cloudinary library. The import path for cloudinary is adjusted accordingly. Additionally, the schema variable is renamed to QuizSchema for clarity and consistency. This change ensures compatibility with the latest cloudinary features and improves the overall codebase.

refactor: Update Quiz model to use cloudinary v2

---

Backend/controllers/Quiz.js
Backend/models/User.js
Backend/routes/Quiz.js
KrishnaAcademyAPP/app/(routes)/quiz/quiz.details.tsx
KrishnaAcademyAPP/utils/uri.tsx

The User model in User.js is updated to include a new questions array field. This field will store the IDs of questions associated with the user. This change allows for better organization and retrieval of user-specific questions.

refactor: Add questions array to User model

---

Backend/controllers/courseBundleController.js
KrishnaAcademyAPP/app/(tabs)/quiz/index.tsx
KrishnaAcademyAPP/screens/search/quiz.screen.tsx

The Search component in the KrishnaAcademyAPP now fetches and displays user-specific quizzes. The code changes in courseBundleController.js and index.tsx retrieve the quizzes associated with the user's courses and bundles. This enhancement improves the functionality of the Search feature and provides a personalized experience for users.

refactor: Fetch and display user-specific quizzes in Search component

---

Backend/routes/courseBundle.js
Backend/utils/otpSender.js
KrishnaAcademyAPP/app/(routes)/enrolled-courses/index.tsx
KrishnaAcademyAPP/app/(routes)/payment/index.tsx
KrishnaAcademyAPP/app/(routes)/quiz-bundle/index.tsx
KrishnaAcademyAPP/app/(routes)/quiz-bundle/styles.tsx
KrishnaAcademyAPP/app/(tabs)/index.tsx
KrishnaAcademyAPP/app/(tabs)/studymaterials/index.tsx
KrishnaAcademyAPP/components/Studymaterials/StudyScreen.tsx
KrishnaAcademyAPP/screens/auth/login/login.screen.tsx
KrishnaAcademyAPP/screens/courses/courses.screen.tsx

This pull request refactors the route path for checking course bundle purchase in the courseBundle.js file. The previous route path '/check-purchase' has been changed to '/checkPurchase' to follow consistent naming conventions. This change ensures that the route is more intuitive and easier to understand for developers working on the project.

Refactor route path for checking course bundle purchase

---

.vscode/settings.json
Backend/controllers/Payments.js
Backend/models/order.js
Backend/routes/courseBundle.js
KrishnaAcademyAPP/app/(routes)/payment/index.tsx
KrishnaAcademyAPP/screens/auth/login/login.screen.tsx
KrishnaAcademyAPP/screens/auth/signup/signup.screen.tsx
KrishnaAcademyAPP/styles/common/common.styles.tsx
KrishnaAcademyAPP/utils/uri.tsx
KrishnaAcademyAPP/yarn.lock

This pull request includes refactoring of the login and signup screens to improve error handling. It also fixes a bug related to order creation and improves error handling in that process. The changes include modifications to the order creation logic, the order schema, and the login and signup screens.

Refactor error handling and fix order creation bug

---

.vscode/settings.json
Backend/routes/courseBundle.js
KrishnaAcademyAPP/app/(routes)/enrolled-courses/index.tsx
KrishnaAcademyAPP/app/(routes)/payment/index.tsx
KrishnaAcademyAPP/app/(routes)/quiz-bundle/index.tsx
KrishnaAcademyAPP/app/(tabs)/index.tsx
KrishnaAcademyAPP/components/header/header.tsx
KrishnaAcademyAPP/screens/search/quiz.screen.tsx

This pull request fixes several UI issues in the code. It updates the width of an image, adjusts the size of a text element, and modifies the styling of a modal. Additionally, the contact information displayed in the modal has been updated to reflect the correct email and phone number.

Fix UI issues and update contact information

---

Backend/index.js

This commit removes unnecessary code and comments from the Backend/index.js file. It improves code readability and reduces clutter in the file.

refactor: Remove unnecessary code and comments

---

AdminDashboard/src/components/common/cpuusage.tsx
AdminDashboard/src/components/core/Dashboard/AddCourse/AllVideo.tsx
AdminDashboard/src/components/core/Dashboard/BundleCourse/CreateBundle.tsx
Backend/controllers/courseBundleController.js
Backend/index.js
Backend/models/CourseBundle.js
Backend/routes/courseBundle.js
KrishnaAcademyAPP/utils/uri.tsx

++Refactor table header label and add video update functionality

---

AdminDashboard/src/components/common/cpuusage.tsx
AdminDashboard/src/services/apis.js
Backend/index.js

The CpuUsageBar component has been refactored to fix an issue with the WebSocket URL. Previously, the URL was not being adjusted correctly, leading to connection errors. This PR updates the WebSocket URL to match the backend URL and ensures that the connection is established successfully.

Refactor CpuUsageBar component to fix WebSocket URL issue
